### PR TITLE
feat: add http tunnel blog post

### PR DESCRIPTION
**Pull request by RafaelGSS**

### CODE REVIEW

**Comment by RafaelGSS** [comment]
Would love to get feedback on this

@mcollina @shogunpanda @micheleriva @codyzu

**Review by mcollina — CHANGES_REQUESTED** [review]
I would go ahead and mention that this is the longer explanation of a CVE fix, and possibly dig a bit deeper on what tools you used to implement and test the fix.

**Comment by ShogunPanda** [comment]
After doing what Matteo suggested, it LGTM!

**Comment by RafaelGSS** [comment]
> I would go ahead and mention that this is the longer explanation of a CVE fix, and possibly dig a bit deeper on what tools you used to implement and test the fix.

Done! Thank you

**Review by ShogunPanda — APPROVED** [review]
LGTM!

**Pull request merged**
